apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: danielstuetz/clc-bmi-consumer:0b21d92        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: danielstuetz/clc-bmi-producer:0b21d92
