apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: danielstuetz/clc-bmi-consumer:7204466      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: danielstuetz/clc-bmi-producer:7204466
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
      - name: bad
        image: danielstuetz/clc-bmi-bad:7204466
